### ISSUE TITLE
Necesito ayuda para instalarlo.

### ISSUE THREAD

**Issue by jeliascabrera** [HuayraLinux/theftdeterrent4#2]
Hola buenas. Querría saber si me pueden ayudar a instalar este paquete en Ubuntu. Me sería de mucha ayuda. Gracias!

**Comment by ftoledo** [comment]
hola @Juane20 , no tenemos ubuntu para probar pero para instalar este paquete, tenes que bajar las dependencias siguientes:

Depends: theftdeterrentclient-lib (>= 6.0.0.11), theftdeterrentdaemon (>= 6.0.0.11), theftdeterrentguardian (>= 6.0.0.11)

Podrías bajar los paquetes .deb desde nuestro repo y probar si instalan bien, sino lamentablemente hay que empaquetarlo para ubuntu:

http://repo.huayra.educar.gob.ar/huayra/pool/non-free/t/theftdeterrent/

**Comment by jeliascabrera** [comment]
@ftoledo Gracias amigo, si no se puede con Ubuntu no me hago drama e instalo Huayra. La idea que tengo es dejarle linux únicamente y cualquiera me serviría. El problema es que instalando el Huayra con el ISO, no viene el Theft Deterrent según tengo entendido.

Pero bueno, gracias, después de que instalo esos tres archivos, ya se instalaría el programa? O cómo debería hacerlo?

**Comment by jeliascabrera** [comment]
> hola @Juane20 , no tenemos ubuntu para probar pero para instalar este paquete, tenes que bajar las dependencias siguientes:
> 
> Depends: theftdeterrentclient-lib (>= 6.0.0.11), theftdeterrentdaemon (>= 6.0.0.11), theftdeterrentguardian (>= 6.0.0.11)
> 
> Podrías bajar los paquetes .deb desde nuestro repo y probar si instalan bien, sino lamentablemente hay que empaquetarlo para ubuntu:
> 
> http://repo.huayra.educar.gob.ar/huayra/pool/non-free/t/theftdeterrent/

Hola amigo, me funcionó perfecto en Ubuntu. Ya pude instalarlo y configurarlo junto con el paquete Huayra-Tdapplet y me funciona sin problemas. Gracias

**Comment by ftoledo** [comment]
> @ftoledo Gracias amigo, si no se puede con Ubuntu no me hago drama e instalo Huayra. La idea que tengo es dejarle linux únicamente y cualquiera me serviría. El problema es que instalando el Huayra con el ISO, no viene el Theft Deterrent según tengo entendido.
> 
> Pero bueno, gracias, después de que instalo esos tres archivos, ya se instalaría el programa? O cómo debería hacerlo?

Claro en la ISO no esta pero hacer apt-get install theftdeterrent y lo instalas desde los repos de Huayra

**Comment by ftoledo** [comment]
> > hola @Juane20 , no tenemos ubuntu para probar pero para instalar este paquete, tenes que bajar las dependencias siguientes:
> > Depends: theftdeterrentclient-lib (>= 6.0.0.11), theftdeterrentdaemon (>= 6.0.0.11), theftdeterrentguardian (>= 6.0.0.11)
> > Podrías bajar los paquetes .deb desde nuestro repo y probar si instalan bien, sino lamentablemente hay que empaquetarlo para ubuntu:
> > http://repo.huayra.educar.gob.ar/huayra/pool/non-free/t/theftdeterrent/
> 
> Hola amigo, me funcionó perfecto en Ubuntu. Ya pude instalarlo y configurarlo junto con el paquete Huayra-Tdapplet y me funciona sin problemas. Gracias

Excelente!!!
